cache:
  directories:
    - "node_modules"
    
install:
    - npm install

before_script:
  - npm run lint
  - npm run build

script:
  - npm run test

language: node_js
node_js:
  - "node"
env:
    - IS_TESTING=true